services:
  vectorizer:
    build:
      context: .
      dockerfile: docker/vectorizer/Dockerfile.gpu
    environment:
      ONNX_PROVIDERS: "CUDAExecutionProvider"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  agent:
    build:
      context: .
      dockerfile: docker/agent/Dockerfile.gpu
    environment:
      ONNX_PROVIDERS: "CUDAExecutionProvider"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
